# Copy this file to config/date.range.yml and make changes as necessary.
#
# This file is only used if `--year` and `--quarter` or `--year` and `--week`
# options are *not* passed to the console application. ...or if the
# `--use-date-config` option *is* explicitly passed with the previously
# mentioned options.
#
# FORMAT:
# Expects two key value pairs, either
#  - `after` and `before`
#     or
#  - `quarter` and `year`
#     or
#  - `week` and `year`.]
#
# EXAMPLE
#     after: 2018-09-30
#     before: 2019-01-01
#
# EXAMPLE
#     quarter: 3
#     year: 2019
# EXAMPLE
#     week: 16
#     year: 2019
#
# You can also pass a year plus a week or quarter option when calling this
# script which will override any option set here. See `by-week.rc` for examples.
after: june 2020
before: july 2021
