# Copy this file to config/date.range.yml and make changes as necessary.
#
# FORMAT:
# Expects two key value pairs, either
#  - `after` and `before`
#     or
#  - `quarter` and `year`
#     or
#  - `week` and `year`.]
#
# EXAMPLE
#     after: 2018-09-30
#     before: 2019-01-01
#
# EXAMPLE
#     quarter: 3
#     year: 2019
# EXAMPLE
#     week: 16
#     year: 2019
#
# You can also pass a week and year option when calling this script which will
# override any option set here. See `by-week.rc` for examples.
quarter: 3
year: 2019
