# Copy this file to config/repos.yml and make changes as necessary.
#
# A list of Git repositories you want to search for commits.
drupal93:
    url: 'https://git.drupal.org/project/drupal.git'
    branch: 9.3.x
